backend:
  name: github
  repo: bitext-api/api-bitext-help # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "apibtx"
    label: "API Bitext Index"
    folder: "source"
    create: false
    fields:
      - {label: "index", name: "API Reference", widget: "markdown"}
